import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Zap,
  Database,
  Table,
  Layers,
  Bell,
  Package,
  Palette,
  Globe,
  Wrench,
  FileEdit,
  CheckSquare,
  Sparkles,
  Moon,
  Shield,
  Settings,
  Move,
  Calendar,
  Bot,
  Code2,
  MessageSquare,
  Cpu,
  Terminal,
  Search,
} from "lucide-react";

export interface Ressource {
  slug: string;
  name: string;
  category: string;
  icon: LucideIcon;
  description: string;
  longDescription: string;
  website: string;
  npmPackage?: string;
  useCases: string[];
  features: string[];
  color: {
    bg: string;
    bgDark: string;
    text: string;
    textDark: string;
  };
}

export const ressources: Ressource[] = [
  {
    slug: "nuqs",
    name: "Nuqs",
    category: "State Management",
    icon: Zap,
    description: "Gestion d'état URL type-safe pour Next.js",
    longDescription:
      "Nuqs est une bibliothèque qui permet de gérer l'état de l'URL de manière type-safe dans Next.js. Elle remplace useSearchParams avec une API beaucoup plus simple et type-safe, permettant de synchroniser l'état de l'application avec l'URL.",
    website: "https://nuqs.47ng.com",
    npmPackage: "nuqs",
    useCases: [
      "Filtres de recherche partageables via URL",
      "Pagination avec URL synchronisée",
      "Tabs avec deep linking",
      "État de tri partageable",
    ],
    features: [
      "Type-safe avec TypeScript",
      "Synchronisation automatique URL/état",
      "SSR compatible",
      "Support des tableaux et objets",
      "Parsing personnalisable",
    ],
    color: {
      bg: "bg-blue-100",
      bgDark: "dark:bg-blue-900/30",
      text: "text-blue-600",
      textDark: "dark:text-blue-400",
    },
  },
  {
    slug: "lucide",
    name: "Lucide",
    category: "Icons",
    icon: Sparkles,
    description: "Bibliothèque d'icônes open-source moderne",
    longDescription:
      "Lucide est une bibliothèque d'icônes open-source avec plus de 1000 icônes. Elle est inspirée de Feather Icons et offre des icônes SVG légères et personnalisables.",
    website: "https://lucide.dev",
    npmPackage: "@lucide/react",
    useCases: [
      "Icônes pour interfaces utilisateur",
      "Icônes de navigation",
      "Icônes d'actions",
      "Icônes de statut",
    ],
    features: [
      "1000+ icônes disponibles",
      "Tree-shakable",
      "Personnalisable (taille, couleur, stroke)",
      "TypeScript support",
      "Accessible par défaut",
    ],
    color: {
      bg: "bg-purple-100",
      bgDark: "dark:bg-purple-900/30",
      text: "text-purple-600",
      textDark: "dark:text-purple-400",
    },
  },
  {
    slug: "tanstack-query",
    name: "TanStack Query",
    category: "Data Fetching",
    icon: Database,
    description: "Gestion d'état serveur puissante et flexible",
    longDescription:
      "TanStack Query (anciennement React Query) est une bibliothèque de gestion d'état serveur qui simplifie la récupération, la mise en cache, la synchronisation et la mise à jour des données serveur dans vos applications React.",
    website: "https://tanstack.com/query",
    npmPackage: "@tanstack/react-query",
    useCases: [
      "Récupération de données API",
      "Cache et invalidation automatique",
      "Mise à jour optimiste",
      "Synchronisation en arrière-plan",
      "Gestion du loading et des erreurs",
    ],
    features: [
      "Cache automatique intelligent",
      "Invalidation et refetch automatiques",
      "Déduplication des requêtes",
      "Background updates",
      "Pagination et infinite scroll",
      "DevTools inclus",
    ],
    color: {
      bg: "bg-cyan-100",
      bgDark: "dark:bg-cyan-900/30",
      text: "text-cyan-600",
      textDark: "dark:text-cyan-400",
    },
  },
  {
    slug: "tanstack-table",
    name: "TanStack Table",
    category: "Tables",
    icon: Table,
    description: "Bibliothèque de tableaux headless et puissante",
    longDescription:
      "TanStack Table est une bibliothèque headless pour construire des tableaux puissants et personnalisables. Elle gère la logique complexe (tri, filtrage, pagination) tout en vous laissant contrôler le rendu.",
    website: "https://tanstack.com/table",
    npmPackage: "@tanstack/react-table",
    useCases: [
      "Tableaux de données complexes",
      "Tri et filtrage avancés",
      "Pagination personnalisée",
      "Sélection de lignes",
      "Colonnes resizables",
    ],
    features: [
      "Headless (contrôle total du rendu)",
      "Tri, filtrage, pagination",
      "Sélection de lignes",
      "Colonnes groupées",
      "Virtualisation",
      "TypeScript complet",
    ],
    color: {
      bg: "bg-emerald-100",
      bgDark: "dark:bg-emerald-900/30",
      text: "text-emerald-600",
      textDark: "dark:text-emerald-400",
    },
  },
  {
    slug: "tanstack-virtual",
    name: "TanStack Virtual",
    category: "Utilities",
    icon: Layers,
    description: "Virtualisation headless pour listes et grilles performantes",
    longDescription:
      "TanStack Virtual est une bibliothèque headless pour virtualiser de longues listes d'éléments. Elle améliore les performances en ne rendant que les éléments visibles dans le DOM, permettant un défilement fluide même avec des milliers d'éléments.",
    website: "https://tanstack.com/virtual",
    npmPackage: "@tanstack/react-virtual",
    useCases: [
      "Listes avec des milliers d'éléments",
      "Grilles virtuelles performantes",
      "Défilement fluide sur grandes listes",
      "Optimisation des performances de rendu",
      "Virtualisation de colonnes et lignes",
    ],
    features: [
      "Headless (contrôle total du rendu)",
      "Virtualisation de listes, colonnes et grilles",
      "Modes de mesure fixes, variables et dynamiques",
      "Contrôle impératif du défilement",
      "Multi-frameworks (React, Vue, Solid, Svelte)",
      "TypeScript complet",
    ],
    color: {
      bg: "bg-teal-100",
      bgDark: "dark:bg-teal-900/30",
      text: "text-teal-600",
      textDark: "dark:text-teal-400",
    },
  },
  {
    slug: "radix-ui",
    name: "Radix UI",
    category: "UI Components",
    icon: Layers,
    description: "Primitives UI accessibles et unstyled",
    longDescription:
      "Radix UI fournit des primitives UI accessibles et unstyled pour React. Chaque composant est entièrement accessible, personnalisable et peut être stylé avec n'importe quelle solution CSS.",
    website: "https://www.radix-ui.com",
    npmPackage: "@radix-ui/react-*",
    useCases: [
      "Composants accessibles (ARIA)",
      "Modals et dialogs",
      "Dropdowns et selects",
      "Tooltips et popovers",
      "Tabs et accordions",
    ],
    features: [
      "100% accessible (WAI-ARIA)",
      "Unstyled (styling total)",
      "Keyboard navigation",
      "Focus management",
      "Portal rendering",
      "TypeScript",
    ],
    color: {
      bg: "bg-violet-100",
      bgDark: "dark:bg-violet-900/30",
      text: "text-violet-600",
      textDark: "dark:text-violet-400",
    },
  },
  {
    slug: "sonner",
    name: "Sonner",
    category: "Notifications",
    icon: Bell,
    description: "Toasts React élégants et personnalisables",
    longDescription:
      "Sonner est une bibliothèque de notifications toast pour React. Elle offre une API simple, des animations fluides et une personnalisation complète.",
    website: "https://sonner.emilkowal.ski",
    npmPackage: "sonner",
    useCases: [
      "Notifications de succès",
      "Messages d'erreur",
      "Notifications d'information",
      "Confirmations d'actions",
    ],
    features: [
      "API simple et intuitive",
      "Animations fluides",
      "Personnalisable",
      "Support du dark mode",
      "Position personnalisable",
      "Promise support",
    ],
    color: {
      bg: "bg-amber-100",
      bgDark: "dark:bg-amber-900/30",
      text: "text-amber-600",
      textDark: "dark:text-amber-400",
    },
  },
  {
    slug: "jotai",
    name: "Jotai",
    category: "State Management",
    icon: Package,
    description: "Gestion d'état atomique pour React",
    longDescription:
      "Jotai est une bibliothèque de gestion d'état atomique pour React. Elle utilise une approche atomique où chaque état est défini comme un atome, permettant une granularité fine et une performance optimale.",
    website: "https://jotai.org",
    npmPackage: "jotai",
    useCases: [
      "État global atomique",
      "État partagé entre composants",
      "État persistant (localStorage)",
      "État dérivé",
    ],
    features: [
      "Approche atomique",
      "Re-renders optimisés",
      "TypeScript",
      "DevTools",
      "Persistance (localStorage, etc.)",
      "Intégration avec React Suspense",
    ],
    color: {
      bg: "bg-indigo-100",
      bgDark: "dark:bg-indigo-900/30",
      text: "text-indigo-600",
      textDark: "dark:text-indigo-400",
    },
  },
  {
    slug: "zustand",
    name: "Zustand",
    category: "State Management",
    icon: Package,
    description: "Gestion d'état légère et simple",
    longDescription:
      "Zustand est une bibliothèque de gestion d'état légère et simple pour React. Elle offre une API minimale sans boilerplate, parfaite pour les applications de taille moyenne.",
    website: "https://zustand-demo.pmnd.rs",
    npmPackage: "zustand",
    useCases: [
      "État global simple",
      "Store centralisé",
      "Persistance (middleware)",
      "Actions et selectors",
    ],
    features: [
      "API simple et intuitive",
      "Léger (< 1KB)",
      "Pas de Provider requis",
      "TypeScript",
      "DevTools support",
      "Middleware (persist, etc.)",
    ],
    color: {
      bg: "bg-pink-100",
      bgDark: "dark:bg-pink-900/30",
      text: "text-pink-600",
      textDark: "dark:text-pink-400",
    },
  },
  {
    slug: "shadcn",
    name: "ShadCn UI",
    category: "UI Components",
    icon: Palette,
    description: "Composants re-utilisables basés sur Radix UI",
    longDescription:
      "ShadCn UI n'est pas un package npm, mais une collection de composants que vous copiez dans votre projet. Basés sur Radix UI et Tailwind CSS, ils sont entièrement personnalisables et accessibles.",
    website: "https://ui.shadcn.com",
    useCases: [
      "Composants UI accessibles",
      "Design system cohérent",
      "Composants personnalisables",
      "Intégration avec Tailwind CSS",
    ],
    features: [
      "Composants accessibles",
      "Basés sur Radix UI",
      "Stylés avec Tailwind CSS",
      "Vous possédez le code",
      "Personnalisable",
      "TypeScript",
    ],
    color: {
      bg: "bg-slate-100",
      bgDark: "dark:bg-slate-900/30",
      text: "text-slate-600",
      textDark: "dark:text-slate-400",
    },
  },
  {
    slug: "tailwindcss",
    name: "Tailwind CSS",
    category: "Styling",
    icon: Palette,
    description: "Framework CSS utility-first",
    longDescription:
      "Tailwind CSS est un framework CSS utility-first qui permet de construire rapidement des interfaces modernes en utilisant des classes utilitaires.",
    website: "https://tailwindcss.com",
    npmPackage: "tailwindcss",
    useCases: [
      "Styling rapide",
      "Design systems",
      "Responsive design",
      "Dark mode",
    ],
    features: [
      "Utility-first",
      "Purge automatique",
      "Dark mode",
      "Responsive design",
      "Personnalisable",
      "Plugins",
    ],
    color: {
      bg: "bg-cyan-100",
      bgDark: "dark:bg-cyan-900/30",
      text: "text-cyan-600",
      textDark: "dark:text-cyan-400",
    },
  },
  {
    slug: "next-intl",
    name: "Next-Intl",
    category: "Internationalization",
    icon: Globe,
    description: "Internationalisation pour Next.js",
    longDescription:
      "Next-Intl est une bibliothèque d'internationalisation pour Next.js qui permet de gérer facilement les traductions et la localisation de votre application.",
    website: "https://next-intl-docs.vercel.app",
    npmPackage: "next-intl",
    useCases: [
      "Applications multilingues",
      "Traductions",
      "Formatage de dates/nombres",
      "Routage par langue",
    ],
    features: [
      "Support SSR/SSG",
      "Type-safe",
      "Formatage automatique",
      "Routage par langue",
      "Lazy loading des traductions",
    ],
    color: {
      bg: "bg-blue-100",
      bgDark: "dark:bg-blue-900/30",
      text: "text-blue-600",
      textDark: "dark:text-blue-400",
    },
  },
  {
    slug: "usehooks-ts",
    name: "usehooks-ts",
    category: "Hooks",
    icon: Wrench,
    description: "Collection de hooks React TypeScript",
    longDescription:
      "usehooks-ts est une collection de hooks React utiles écrits en TypeScript. Elle offre des hooks pour des cas d'usage courants comme localStorage, debounce, etc.",
    website: "https://usehooks-ts.com",
    npmPackage: "usehooks-ts",
    useCases: [
      "Hooks utilitaires",
      "localStorage/sessionStorage",
      "Debounce/throttle",
      "Media queries",
      "Intersection observer",
    ],
    features: [
      "TypeScript",
      "Tree-shakable",
      "Hooks testés",
      "Documentation complète",
    ],
    color: {
      bg: "bg-orange-100",
      bgDark: "dark:bg-orange-900/30",
      text: "text-orange-600",
      textDark: "dark:text-orange-400",
    },
  },
  {
    slug: "react-hook-form",
    name: "React Hook Form",
    category: "Forms",
    icon: FileEdit,
    description: "Gestion de formulaires performante",
    longDescription:
      "React Hook Form est une bibliothèque de gestion de formulaires pour React qui minimise les re-renders et offre une excellente performance grâce à l'utilisation de refs non contrôlées.",
    website: "https://react-hook-form.com",
    npmPackage: "react-hook-form",
    useCases: [
      "Formulaires complexes",
      "Validation",
      "Performance optimale",
      "Intégration avec Zod",
    ],
    features: [
      "Performance optimale",
      "Validation intégrée",
      "Intégration Zod/Yup",
      "TypeScript",
      "DevTools",
      "Accessible",
    ],
    color: {
      bg: "bg-red-100",
      bgDark: "dark:bg-red-900/30",
      text: "text-red-600",
      textDark: "dark:text-red-400",
    },
  },
  {
    slug: "zod",
    name: "Zod",
    category: "Validation",
    icon: CheckSquare,
    description: "Validation TypeScript-first avec inference",
    longDescription:
      "Zod est une bibliothèque de validation TypeScript-first qui permet de définir des schémas de validation et d'inférer automatiquement les types TypeScript.",
    website: "https://zod.dev",
    npmPackage: "zod",
    useCases: [
      "Validation de formulaires",
      "Validation d'API",
      "Type inference",
      "Parsing de données",
    ],
    features: [
      "Type-safe",
      "Type inference",
      "Composable",
      "Erreurs détaillées",
      "Intégration avec React Hook Form",
    ],
    color: {
      bg: "bg-green-100",
      bgDark: "dark:bg-green-900/30",
      text: "text-green-600",
      textDark: "dark:text-green-400",
    },
  },
  {
    slug: "onboarda",
    name: "Onboarda",
    category: "Onboarding",
    icon: Sparkles,
    description: "Bibliothèque d'onboarding interactive",
    longDescription:
      "Onboarda est une bibliothèque pour créer des expériences d'onboarding interactives, des tooltips guidés et des tours de fonctionnalités.",
    website: "https://onboarda.dev",
    npmPackage: "onboarda",
    useCases: [
      "Tours de fonctionnalités",
      "Onboarding utilisateurs",
      "Tooltips guidés",
      "Popovers interactifs",
    ],
    features: [
      "API simple",
      "Personnalisable",
      "Animations fluides",
      "Keyboard navigation",
      "Accessible",
    ],
    color: {
      bg: "bg-purple-100",
      bgDark: "dark:bg-purple-900/30",
      text: "text-purple-600",
      textDark: "dark:text-purple-400",
    },
  },
  {
    slug: "storybook",
    name: "Storybook",
    category: "Development",
    icon: BookOpen,
    description: "Environnement de développement pour composants UI",
    longDescription:
      "Storybook est un outil de développement pour créer et tester des composants UI de manière isolée. Il permet de documenter, tester et développer des composants indépendamment de l'application.",
    website: "https://storybook.js.org",
    npmPackage: "@storybook/react",
    useCases: [
      "Développement de composants isolés",
      "Documentation de composants",
      "Tests visuels",
      "Design system",
    ],
    features: [
      "Développement isolé",
      "Documentation interactive",
      "Tests visuels",
      "Addons",
      "Intégration CI/CD",
    ],
    color: {
      bg: "bg-pink-100",
      bgDark: "dark:bg-pink-900/30",
      text: "text-pink-600",
      textDark: "dark:text-pink-400",
    },
  },
  {
    slug: "next-themes",
    name: "next-themes",
    category: "Styling",
    icon: Moon,
    description: "Gestion du thème (dark mode) pour Next.js",
    longDescription:
      "next-themes est une bibliothèque qui permet de gérer facilement le thème (light/dark mode) dans les applications Next.js. Elle gère la persistance du thème, évite les flashs de contenu et offre une API simple.",
    website: "https://github.com/pacocoursey/next-themes",
    npmPackage: "next-themes",
    useCases: [
      "Dark mode / Light mode",
      "Thème système automatique",
      "Persistance du thème",
      "Toggle de thème",
    ],
    features: [
      "Pas de flash de contenu (FOUC)",
      "Support SSR",
      "Persistance (localStorage)",
      "Détection du thème système",
      "API simple",
      "TypeScript",
    ],
    color: {
      bg: "bg-slate-100",
      bgDark: "dark:bg-slate-900/30",
      text: "text-slate-600",
      textDark: "dark:text-slate-400",
    },
  },
  {
    slug: "t3-env",
    name: "t3-env",
    category: "Development",
    icon: Settings,
    description: "Variables d'environnement type-safe avec validation",
    longDescription:
      "t3-env est une bibliothèque qui permet de gérer les variables d'environnement de manière type-safe avec validation Zod. Elle garantit que toutes les variables nécessaires sont présentes et valides au build time.",
    website: "https://env.t3.gg",
    npmPackage: "@t3-oss/env-nextjs",
    useCases: [
      "Validation des variables d'environnement",
      "Type safety pour les env vars",
      "Erreurs au build time",
      "Documentation automatique",
    ],
    features: [
      "Type-safe avec TypeScript",
      "Validation avec Zod",
      "Erreurs au build time",
      "Support Next.js / Nuxt / Vite",
      "Séparation client/server",
      "Documentation automatique",
    ],
    color: {
      bg: "bg-amber-100",
      bgDark: "dark:bg-amber-900/30",
      text: "text-amber-600",
      textDark: "dark:text-amber-400",
    },
  },
  {
    slug: "better-auth",
    name: "Better Auth",
    category: "Authentication",
    icon: Shield,
    description: "Bibliothèque d'authentification moderne et type-safe",
    longDescription:
      "Better Auth est une bibliothèque d'authentification complète et moderne pour Next.js et autres frameworks. Elle offre une API type-safe, supporte de nombreux providers (OAuth, email/password, etc.) et est entièrement personnalisable.",
    website: "https://better-auth.com",
    npmPackage: "better-auth",
    useCases: [
      "Authentification email/password",
      "OAuth (Google, GitHub, etc.)",
      "Gestion de sessions",
      "2FA (Two-Factor Authentication)",
      "Mise à jour de profil",
    ],
    features: [
      "Type-safe avec TypeScript",
      "Support OAuth multiple",
      "Email/password",
      "2FA",
      "Sessions sécurisées",
      "Middleware Next.js",
      "Personnalisable",
      "SSR support",
    ],
    color: {
      bg: "bg-blue-100",
      bgDark: "dark:bg-blue-900/30",
      text: "text-blue-600",
      textDark: "dark:text-blue-400",
    },
  },
  {
    slug: "dnd-kit",
    name: "dnd kit",
    category: "UI Components",
    icon: Move,
    description: "Bibliothèque de drag and drop accessible pour React",
    longDescription:
      "dnd kit est une bibliothèque moderne et accessible pour implémenter le drag and drop dans React. Elle offre une API simple, une excellente accessibilité (ARIA) et une performance optimale.",
    website: "https://dndkit.com",
    npmPackage: "@dnd-kit/core",
    useCases: [
      "Listes réorganisables",
      "Kanban boards",
      "Tableaux avec colonnes déplaçables",
      "Formulaires avec champs réorganisables",
      "Galleries d'images réorganisables",
    ],
    features: [
      "Accessible (ARIA compliant)",
      "TypeScript",
      "Performance optimale",
      "API simple et intuitive",
      "Support tactile",
      "Personnalisable",
      "Sensors multiples",
    ],
    color: {
      bg: "bg-violet-100",
      bgDark: "dark:bg-violet-900/30",
      text: "text-violet-600",
      textDark: "dark:text-violet-400",
    },
  },
  {
    slug: "dayjs",
    name: "Day.js",
    category: "Utilities",
    icon: Calendar,
    description: "Bibliothèque de manipulation de dates légère et moderne",
    longDescription:
      "Day.js est une bibliothèque JavaScript moderne et légère pour manipuler les dates. Alternative légère à Moment.js, elle offre une API similaire avec un bundle beaucoup plus petit (2KB vs 67KB).",
    website: "https://day.js.org",
    npmPackage: "dayjs",
    useCases: [
      "Formatage de dates",
      "Calculs de dates (ajout, soustraction)",
      "Parsing de dates",
      "Comparaison de dates",
      "Manipulation de timezones",
      "Localisation",
    ],
    features: [
      "Léger (2KB)",
      "API similaire à Moment.js",
      "Immutable",
      "Chainable",
      "Plugins extensibles",
      "TypeScript",
      "i18n support",
    ],
    color: {
      bg: "bg-indigo-100",
      bgDark: "dark:bg-indigo-900/30",
      text: "text-indigo-600",
      textDark: "dark:text-indigo-400",
    },
  },
  {
    slug: "dust",
    name: "Dust",
    category: "AI Agents",
    icon: Bot,
    description: "Plateforme pour créer des agents IA en minutes",
    longDescription:
      "Dust est une plateforme qui permet de créer des agents IA personnalisés en quelques minutes, connectés aux connaissances et outils de votre entreprise. Les agents sont alimentés par les meilleurs modèles IA et peuvent être déployés rapidement.",
    website: "https://dust.tt",
    useCases: [
      "Agents pour les ventes et le support client",
      "Agents pour le marketing et le contenu",
      "Agents pour l'ingénierie et le développement",
      "Agents pour l'analyse de données",
      "Agents pour la gestion des connaissances",
    ],
    features: [
      "Création d'agents sans code",
      "Connexion aux données d'entreprise",
      "Intégration avec outils existants",
      "Orchestration d'équipes d'agents",
      "Sécurité et conformité (SOC 2, GDPR)",
    ],
    color: {
      bg: "bg-blue-100",
      bgDark: "dark:bg-blue-900/30",
      text: "text-blue-600",
      textDark: "dark:text-blue-400",
    },
  },
  {
    slug: "crewai",
    name: "CrewAI",
    category: "AI Agents",
    icon: Bot,
    description: "Framework pour créer des équipes d'agents IA collaboratifs",
    longDescription:
      "CrewAI est un framework Python qui permet de créer des équipes d'agents IA spécialisés qui collaborent ensemble pour résoudre des tâches complexes. Chaque agent a un rôle et des outils spécifiques.",
    website: "https://www.crewai.com",
    npmPackage: "crewai",
    useCases: [
      "Équipes d'agents pour la recherche",
      "Agents collaboratifs pour l'analyse",
      "Automatisation de workflows complexes",
      "Agents spécialisés par domaine",
    ],
    features: [
      "Agents collaboratifs",
      "Rôles et responsabilités définis",
      "Outils personnalisables",
      "Planification de tâches",
      "Python-first",
    ],
    color: {
      bg: "bg-indigo-100",
      bgDark: "dark:bg-indigo-900/30",
      text: "text-indigo-600",
      textDark: "dark:text-indigo-400",
    },
  },
  {
    slug: "ai-sdk",
    name: "AI SDK",
    category: "AI SDK",
    icon: Code2,
    description: "SDK pour intégrer l'IA dans vos applications",
    longDescription:
      "AI SDK (Vercel AI SDK) est un kit de développement qui simplifie l'intégration de modèles IA dans vos applications. Il supporte de nombreux fournisseurs (OpenAI, Anthropic, Google, etc.) avec une API unifiée.",
    website: "https://ai-sdk.dev",
    npmPackage: "@ai-sdk/core",
    useCases: [
      "Intégration de modèles IA dans Next.js",
      "Streaming de réponses",
      "Génération de texte et de chat",
      "Embeddings et vectorisation",
    ],
    features: [
      "API unifiée multi-fournisseurs",
      "Streaming natif",
      "TypeScript first",
      "Framework agnostic",
      "Hooks React intégrés",
    ],
    color: {
      bg: "bg-purple-100",
      bgDark: "dark:bg-purple-900/30",
      text: "text-purple-600",
      textDark: "dark:text-purple-400",
    },
  },
  {
    slug: "mastra",
    name: "Mastra",
    category: "AI SDK",
    icon: Code2,
    description: "Framework full-stack pour applications IA",
    longDescription:
      "Mastra est un framework full-stack qui facilite la création d'applications IA. Il fournit des outils pour la gestion des prompts, la vectorisation, et l'intégration avec différents modèles IA.",
    website: "https://mastra.ai",
    useCases: [
      "Applications IA full-stack",
      "Gestion de prompts",
      "Vectorisation et recherche",
      "Intégration multi-modèles",
    ],
    features: [
      "Framework full-stack",
      "Gestion de prompts",
      "Vectorisation intégrée",
      "Multi-modèles support",
      "TypeScript",
    ],
    color: {
      bg: "bg-pink-100",
      bgDark: "dark:bg-pink-900/30",
      text: "text-pink-600",
      textDark: "dark:text-pink-400",
    },
  },
  {
    slug: "librechat",
    name: "LibreChat",
    category: "AI Chat",
    icon: MessageSquare,
    description: "Interface de chat open-source pour modèles IA",
    longDescription:
      "LibreChat est une interface de chat open-source qui permet de converser avec différents modèles IA. Elle supporte OpenAI, Anthropic, Google, et bien d'autres fournisseurs avec une interface unifiée.",
    website: "https://www.librechat.ai",
    useCases: [
      "Interface de chat pour équipes",
      "Support multi-fournisseurs",
      "Gestion de conversations",
      "Personnalisation de l'interface",
    ],
    features: [
      "Open-source",
      "Multi-fournisseurs",
      "Interface personnalisable",
      "Gestion de conversations",
      "Self-hosted",
    ],
    color: {
      bg: "bg-green-100",
      bgDark: "dark:bg-green-900/30",
      text: "text-green-600",
      textDark: "dark:text-green-400",
    },
  },
  {
    slug: "pipelex",
    name: "Pipelex",
    category: "AI Chat",
    icon: MessageSquare,
    description: "Plateforme de chat IA conversationnelle",
    longDescription:
      "Pipelex est une plateforme qui permet de créer des expériences de chat IA avancées. Elle offre des outils pour la gestion de conversations, l'analyse de texte, et l'intégration avec différents modèles.",
    website: "https://www.pipelex.com",
    useCases: [
      "Chatbots conversationnels",
      "Support client automatisé",
      "Analyse de conversations",
      "Intégration de modèles IA",
    ],
    features: [
      "Chat conversationnel",
      "Analyse de texte",
      "Multi-modèles",
      "API flexible",
      "Analytics intégrés",
    ],
    color: {
      bg: "bg-cyan-100",
      bgDark: "dark:bg-cyan-900/30",
      text: "text-cyan-600",
      textDark: "dark:text-cyan-400",
    },
  },
  {
    slug: "onyx",
    name: "Onyx",
    category: "AI Chat",
    icon: MessageSquare,
    description: "Application de chat IA moderne",
    longDescription:
      "Onyx est une application de chat IA qui offre une expérience utilisateur moderne pour interagir avec différents modèles de langage. Elle se concentre sur la simplicité et la performance.",
    website: "https://www.onyx.app",
    useCases: [
      "Chat personnel avec IA",
      "Interface moderne et intuitive",
      "Support multi-modèles",
      "Expérience utilisateur optimisée",
    ],
    features: [
      "Interface moderne",
      "Performance optimale",
      "Multi-modèles",
      "Expérience utilisateur soignée",
    ],
    color: {
      bg: "bg-slate-100",
      bgDark: "dark:bg-slate-900/30",
      text: "text-slate-600",
      textDark: "dark:text-slate-400",
    },
  },
  {
    slug: "ollama",
    name: "Ollama",
    category: "Local AI",
    icon: Cpu,
    description: "Exécuter des modèles IA localement sur votre machine",
    longDescription:
      "Ollama permet d'exécuter des modèles de langage localement sur votre machine, sans connexion internet. Il supporte de nombreux modèles open-source comme Llama, Mistral, et bien d'autres.",
    website: "https://ollama.com",
    useCases: [
      "Exécution locale de modèles IA",
      "Développement sans API externe",
      "Confidentialité des données",
      "Expérimentation avec modèles open-source",
    ],
    features: [
      "Exécution locale",
      "Multi-modèles supportés",
      "API simple",
      "Gestion automatique des modèles",
      "Cross-platform",
    ],
    color: {
      bg: "bg-orange-100",
      bgDark: "dark:bg-orange-900/30",
      text: "text-orange-600",
      textDark: "dark:text-orange-400",
    },
  },
  {
    slug: "lmstudio",
    name: "LM Studio",
    category: "Local AI",
    icon: Cpu,
    description: "Interface graphique pour exécuter des modèles IA localement",
    longDescription:
      "LM Studio est une application desktop qui permet de télécharger, gérer et exécuter des modèles de langage localement sur votre machine. Elle offre une interface graphique intuitive pour interagir avec les modèles.",
    website: "https://lmstudio.ai",
    useCases: [
      "Interface graphique pour modèles locaux",
      "Gestion de modèles IA",
      "Chat local avec IA",
      "Expérimentation sans code",
    ],
    features: [
      "Interface graphique",
      "Gestion de modèles",
      "Chat intégré",
      "Multi-modèles supportés",
      "Cross-platform",
    ],
    color: {
      bg: "bg-amber-100",
      bgDark: "dark:bg-amber-900/30",
      text: "text-amber-600",
      textDark: "dark:text-amber-400",
    },
  },
  {
    slug: "v0",
    name: "v0",
    category: "AI Code Generation",
    icon: Terminal,
    description: "Génération de composants UI avec IA",
    longDescription:
      "v0 est un outil de Vercel qui génère des composants React/Next.js à partir de descriptions textuelles. Il utilise l'IA pour créer des interfaces utilisateur modernes et fonctionnelles.",
    website: "https://v0.dev",
    useCases: [
      "Génération rapide de composants UI",
      "Prototypage d'interfaces",
      "Inspiration de design",
      "Composants React/Next.js",
    ],
    features: [
      "Génération de composants React",
      "Intégration ShadCN UI",
      "Code prêt à l'emploi",
      "Interface simple",
      "Gratuit",
    ],
    color: {
      bg: "bg-violet-100",
      bgDark: "dark:bg-violet-900/30",
      text: "text-violet-600",
      textDark: "dark:text-violet-400",
    },
  },
  {
    slug: "bolt",
    name: "Bolt.new",
    category: "AI Code Generation",
    icon: Terminal,
    description: "Agent de développement web full-stack alimenté par IA",
    longDescription:
      "Bolt.new est un agent de développement web full-stack qui permet de créer, exécuter, éditer et déployer des applications directement depuis le navigateur. Aucune configuration locale requise.",
    website: "https://bolt.new",
    useCases: [
      "Développement web rapide",
      "Prototypage d'applications",
      "Développement sans configuration",
      "Applications full-stack",
    ],
    features: [
      "Développement dans le navigateur",
      "Full-stack",
      "Déploiement intégré",
      "Pas de configuration",
      "IA intégrée",
    ],
    color: {
      bg: "bg-red-100",
      bgDark: "dark:bg-red-900/30",
      text: "text-red-600",
      textDark: "dark:text-red-400",
    },
  },
  {
    slug: "lovable",
    name: "Lovable",
    category: "AI Code Generation",
    icon: Terminal,
    description: "Plateforme de développement assisté par IA",
    longDescription:
      "Lovable est une plateforme qui permet de créer des applications web complètes avec l'aide de l'IA. Elle combine génération de code, édition et déploiement dans une seule interface.",
    website: "https://lovable.dev",
    useCases: [
      "Création d'applications web",
      "Développement assisté par IA",
      "Prototypage rapide",
      "Applications complètes",
    ],
    features: [
      "Génération de code IA",
      "Édition en temps réel",
      "Déploiement automatique",
      "Applications complètes",
      "Interface intuitive",
    ],
    color: {
      bg: "bg-emerald-100",
      bgDark: "dark:bg-emerald-900/30",
      text: "text-emerald-600",
      textDark: "dark:text-emerald-400",
    },
  },
  {
    slug: "deepwiki",
    name: "DeepWiki",
    category: "AI Documentation",
    icon: Search,
    description: "Documentation à jour pour chaque repo GitHub",
    longDescription:
      "DeepWiki fournit une documentation à jour que vous pouvez interroger, pour chaque repository GitHub. Pensez à Deep Research pour GitHub - une documentation complète et interactive pour comprendre n'importe quel projet.",
    website: "https://deepwiki.org",
    useCases: [
      "Comprendre des projets GitHub",
      "Documentation interactive",
      "Recherche dans le code",
      "Onboarding sur nouveaux projets",
    ],
    features: [
      "Documentation à jour",
      "Interface conversationnelle",
      "Support multi-repos",
      "Recherche intelligente",
      "Gratuit",
    ],
    color: {
      bg: "bg-teal-100",
      bgDark: "dark:bg-teal-900/30",
      text: "text-teal-600",
      textDark: "dark:text-teal-400",
    },
  },
];

export const categories = [
  "State Management",
  "Data Fetching",
  "UI Components",
  "Forms",
  "Validation",
  "Styling",
  "Icons",
  "Notifications",
  "Internationalization",
  "Hooks",
  "Onboarding",
  "Development",
  "Tables",
  "Authentication",
  "Utilities",
  "AI Agents",
  "AI SDK",
  "AI Chat",
  "Local AI",
  "AI Code Generation",
  "AI Documentation",
] as const;

export function getRessourceBySlug(slug: string): Ressource | undefined {
  return ressources.find((r) => r.slug === slug);
}

export function getRessourcesByCategory(category: string): Ressource[] {
  return ressources.filter((r) => r.category === category);
}
